import Head from "next/head";

import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import { useEffect } from "react";
import dayjs from "dayjs";
import { signIn } from "next-auth/react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const now = dayjs();
  
  useEffect(() => {
    axios
      .get("/api/login")
      .then(() => {
        router.push(`/calendar/${now.year()}/${now.month() + 1}`);
        return;
      })
      .catch(() => {
        signIn("cognito");
      });
    // if (session?.user) {

    // }
  }, []);
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
    </>
  );
}
