import Head from "next/head";

import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import { useEffect } from "react";
import dayjs from "dayjs";
import { signIn, useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const now = dayjs();
  const { data: session } = useSession();
  useEffect(() => {
    if (session?.user) {
      router.push(`/calendar/${now.year()}/${now.month() + 1}`);
      return;
    }
  }, [now, router, router.isReady]);
  return (
    <>
      <Head>
        <title>Calendar</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
    </>
  );
}
